export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SYSTEM_ERROR = 'AUTH_SYSTEM_ERROR';
export const LOGOUT = 'LOGOUT';
export const COOKIE_CHECKED = 'COOKIE_CHECKED';

export const CONVERT_DATE = 'CONVERT_RUPIAH';
export const CONVERT_RUPIAH = 'CONVERT_RUPIAH';

export const GET_FLIGHT_LIST_SUCCESS = 'GET_FLIGHT_LIST_SUCCESS';
export const GET_FLIGHT_LIST_FAIL = 'GET_FLIGHT_LIST_FAIL';
